---
spring:
  profiles: production
value: teste1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:password@localhost:8761/eureka/
      
server:
  port: 9090
