---
spring:
  profiles:
    active: production
zuul:
  routes:
    rest-service:
      path: /**
      serviceId: rest-service
  prefix: /api
  sensitive-headers:
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:password@localhost:8761/eureka/
